datapath: /devdata/hsh/datasets/seg_dataset/BraTS2018_remove0_normalize_nii_resize128/MICCAI_BraTS_2018_Data_Training
train_list: datalist/BraTS18/BraTS18_train.txt
val_list: datalist/BraTS18/BraTS18_val.txt
snapshot_dir:
method_name: CLRSNet
dataname: BRATS2018

input_size: [128,128,128]
num_gpus:
local_rank: 0
print_rank: 0

batch_size: 1
batch_size_val: 1
num_workers: 0

num_cls: 3
num_modality: 4
normalization: batchnorm
spec_normalization: batchnorm

coe_specloss: 0.1
coe_consist: 0.1

optim: sgd   # adam adam  adamw
lr_scheduler: PolyLR  # PolyLR LambdaLR
learning_rate_fate: 0.01
lr: 0.0002  # 2e-4
weight_decay: 0.0001 # 1e-4
num_epochs: 200
iter_per_epoch:

aux:
  optim: adam   # sgd adam  adamw
  lr_scheduler: PolyLR  # PolyLR LambdaLR StepLR
  learning_rate_fate: 0.01
  lr: 0.0001 # 2e-4
  weight_decay: 0.0001 # 1e-4
  num_epochs: 200
  iter_per_epoch:
  normalization: IN

region_fusion_start_epoch: 0
resume: null
pretrain: null
seed: 1024

ignore_label: 255
is_training: True
random_mirror: True
random_scale: True
norm_cfg: BN
activation_cfg: LeakyReLU
train_only: False  #
mode: random   # 0 , 1, 2,3  random